name: timedp
channels:
  - nvidia
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - antlr-python-runtime=4.9.3
  - anyio=4.5.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=2.120
  - blas-devel=3.9.0
  - bleach=6.1.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.1.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.7.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diffusers=0.18.2
  - diffusers-base=0.18.2
  - diffusers-torch=0.18.2
  - docker-pycreds=0.4.0
  - einops=0.8.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ffmpeg=7.1.0
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2024.10.0
  - future=1.0.0
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.86.1
  - glib-tools=2.86.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.6.0
  - harfbuzz=9.0.0
  - hdf5=1.12.1
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.27.2
  - huggingface_accelerate=1.0.1
  - huggingface_hub=0.24.6
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.10.0
  - jupyter_server=2.13.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.3
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20240116.2
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.16.0
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgrpc=1.62.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnpp=11.7.4.75
  - libnsl=2.0.1
  - libnvjpeg=11.8.0.2
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mkl=2023.2.0
  - mkl-devel=2023.2.0
  - mkl-include=2023.2.0
  - munkres=1.1.4
  - mysql=8.4.0
  - nbclassic=1.1.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - numpy=1.19.2
  - ocl-icd=2.3.3
  - omegaconf=2.3.0
  - opencl-headers=2025.06.13
  - openh264=2.4.1
  - openjpeg=2.5.0
  - openldap=2.6.10
  - openssl=3.5.4
  - overrides=7.7.0
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=20.3.4
  - pixman=0.46.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydeprecate=0.3.1
  - pygments=2.18.0
  - pyparsing=3.1.4
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python_abi=3.8
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pytorch-lightning=1.4.2
  - pytorch-mutex=1.0
  - pytz=2024.2
  - pywavelets=1.4.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - regex=2024.9.11
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - safetensors=0.4.4
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.3
  - sentry-sdk=2.19.2
  - setproctitle=1.3.3
  - setuptools=69.5.1
  - sip=6.5.1
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.6
  - sqlite=3.50.4
  - stack_data=0.6.2
  - statsmodels=0.13.2
  - svt-av1=2.2.1
  - tbb=2021.13.0
  - tensorboard=2.17.1
  - tensorboard-data-server=0.7.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.2
  - torchaudio=0.13.0
  - torchmetrics=0.7.3
  - torchvision=0.14.0
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wandb=0.16.6
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.6
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrender=0.9.12
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - et-xmlfile==2.0.0
      - openpyxl==3.1.5
      - torchsummary==1.5.1
prefix: /home/xyr/miniconda3/envs/timedp
